# Generated by Django 3.1.1 on 2020-09-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avilable',
            new_name='available',
        ),
    ]
